- name: sync dnsmasq hosts with inventory
  hosts: localhost
  gather_facts: false
  tasks:

  - name: generate dnsmasq.conf
    template:
      src: 'dnsmasq.j2'
      dest: '/etc/dnsmasq.conf'
    register: dnsmasq

  - name: test dnsmasq config
    shell: 'dnsmasq --test'
    when: dnsmasq is changed

  - name: restart dnsmasq service
    systemd:
      name: dnsmasq
      state: restarted
    when: dnsmasq is changed
